---
title: "comparison anova"
format: pdf
---

```{r setup, include=FALSE}
#Initial Code Chunk
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(tidyverse)
library(ggthemes)
library(readr)
library(patchwork)
library(car)

diabeted_multiclass <- read_csv("../data/diabeted_multiclass.csv")
```

```{r}
#Data Set Up
data <- diabeted_multiclass %>% 
  select(Diabetes_012,
         BMI)

data$Diabetes_012 <- factor(data$Diabetes_012,
                            levels = c(0, 1, 2),
                            labels = c("no_diabetes", "prediabetes", "diabetes"))
glimpse(data)
```

```{r}
data %>% 
  ggplot()+
  geom_bar(aes(x = Diabetes_012))+
  theme_few()
```
Differences in sizes of groups. We will make them all the same size.


```{r}
n <- nrow(data[data$Diabetes_012 == "prediabetes", ])

prediabetes <- data[data$Diabetes_012 == "prediabetes", ]
no_diabetes <- slice_sample(data[data$Diabetes_012 == "no_diabetes", ], n=n)
diabetes <- slice_sample(data[data$Diabetes_012 == "diabetes", ], n=n)

test_data <- bind_rows(prediabetes, no_diabetes, diabetes)
```



### Parametric Anova

```{r}
# The ANOVA MODEl
anova_model <- aov(BMI ~ Diabetes_012, test_data)
summary(anova_model)
```

```{r}
# Assumptions Check
# Normal Errors
qqnorm(residuals(anova_model))
qqline(residuals(anova_model), col = "red")
```

Serious Divergence from Normality

```{r}
#Assumptions Check
#Homoskadacity
sds <- tapply(test_data$BMI, test_data$Diabetes_012, sd, na.rm = TRUE)
ratio <- max(sds[1]) / min(sds[3])
ratio

leveneTest(BMI ~ Diabetes_012, data = test_data)
```
```{r}
# Welch's ANOVA
oneway.test(BMI ~ Diabetes_012, data = diabeted_multiclass, var.equal = FALSE)
```

### Nonparametric - Kruskal Wallis

```{r}
#assumption - same distributions
p_0 <- test_data %>% 
  filter(Diabetes_012 == "no_diabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("No Diabetes")

p_1 <- test_data %>% 
  filter(Diabetes_012 == "prediabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("Pre-Diabetes")

p_2 <- test_data %>% 
  filter(Diabetes_012 == "diabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("Diabetes")

p_0 + p_1 + p_2
```

Same distribution across

```{r}
kruskal.test(BMI ~ Diabetes_012, data = data)
pairwise.wilcox.test(data$BMI, data$Diabetes_012, p.adjust.method = "bonferroni")
```

