---
title: "kruskal-wallis"
format: pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(tidyverse)
library(ggthemes)
library(readr)
library(patchwork)

diabeted_multiclass <- read_csv("../data/diabeted_multiclass.csv")
```


```{r}
data <- diabeted_multiclass %>% 
  select(Diabetes_012,
         BMI)

data$Diabetes_012 <- factor(data$Diabetes_012,
                            levels = c(0, 1, 2),
                            labels = c("No Diabetes", "Prediabetes", "Diabetes"))
glimpse(data)
```

```{r}
summary(data$BMI)
```

```{r}
hist(data$BMI)
```
```{r}
p_0 <- data %>% 
  filter(Diabetes_012 == "No Diabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("No Diabetes")

p_1 <- data %>% 
  filter(Diabetes_012 == "Prediabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("Pre-Diabetes")

p_2 <- data %>% 
  filter(Diabetes_012 == "Diabetes") %>% 
  ggplot()+
  geom_histogram(aes(x = BMI),
                 fill = "black")+
  theme_few()+
  ggtitle("Diabetes")

p_0 + p_1 + p_2
```


```{r}
data %>% 
  ggplot()+
  geom_bar(aes(x = Diabetes_012),
           fill = "black") +
  theme_few()+
  xlab("")+
  ggtitle("Distribution of Daibetes Factor")
```




```{r}
ggplot(data, aes(x = Diabetes_012, y = BMI)) +
  geom_boxplot() +
  labs(title = "BMI Distribution by Diabetes Status",
       x = "",
       y = "BMI") +
  theme_minimal()
```




```{r}
kruskal.test(BMI ~ Diabetes_012, data = data)
```


```{r}
pairwise.wilcox.test(data$BMI, data$Diabetes_012, p.adjust.method = "bonferroni")
```


